function setup_paths()
    % SETUP_PATHS Configures MATLAB search paths for SIH26037 Autonomous Pipeline
    %
    % Integrates the decoupled architectural layers:
    %   1. simulation_environment/  (Scenarios, traffic, world, sensors, plant)
    %   2. autonomy_pipeline/       (Perception, decision, planning, optimization_qp, safety, control)
    %   3. Supporting modules       (config, stages, metrics, visualization, scripts, tests)
    
    root_dir = fileparts(mfilename('fullpath'));
    
    % Autonomy Pipeline Subdirectories
    autonomy_dirs = {
        fullfile(root_dir, 'autonomy_pipeline'), ...
        fullfile(root_dir, 'autonomy_pipeline', 'perception_tracking'), ...
        fullfile(root_dir, 'autonomy_pipeline', 'decision'), ...
        fullfile(root_dir, 'autonomy_pipeline', 'planning'), ...
        fullfile(root_dir, 'autonomy_pipeline', 'optimization_qp'), ...
        fullfile(root_dir, 'autonomy_pipeline', 'safety'), ...
        fullfile(root_dir, 'autonomy_pipeline', 'control')
    };
    
    % Simulation Environment Subdirectories
    sim_dirs = {
        fullfile(root_dir, 'simulation_environment'), ...
        fullfile(root_dir, 'simulation_environment', 'scenarios'), ...
        fullfile(root_dir, 'simulation_environment', 'traffic'), ...
        fullfile(root_dir, 'simulation_environment', 'world'), ...
        fullfile(root_dir, 'simulation_environment', 'sensors'), ...
        fullfile(root_dir, 'simulation_environment', 'plant')
    };
    
    % Core Support Subdirectories
    support_dirs = {
        fullfile(root_dir, 'config'), ...
        fullfile(root_dir, 'stages'), ...
        fullfile(root_dir, 'metrics'), ...
        fullfile(root_dir, 'visualization'), ...
        fullfile(root_dir, 'scripts'), ...
        fullfile(root_dir, 'tests')
    };
    
    % Legacy compatibility paths (symlink backed)
    legacy_dirs = {
        fullfile(root_dir, 'planning'), ...
        fullfile(root_dir, 'environment'), ...
        fullfile(root_dir, 'vehicle'), ...
        fullfile(root_dir, 'core')
    };
    
    all_dirs = [autonomy_dirs, sim_dirs, support_dirs, legacy_dirs];
    
    added_count = 0;
    for i = 1:length(all_dirs)
        d = all_dirs{i};
        if exist(d, 'dir')
            addpath(d);
            added_count = added_count + 1;
        end
    end
    
    fprintf('[setup_paths] Configured %d paths across Autonomy Pipeline and Simulation Environment.\n', added_count);
end
